Fix BE regex
ddeboer/vatin pull request #43
Opened 2023-08-04 14:15 UTC by neodc

`|` are not allowed in Belgian numbers

2023-08-04 15:14 UTC, GrahamCampbell requested changes
This change is wrong, since it now insists on 0 THEN 1 THEN 9 DIGITS, rather than 0 OR 1 THEN 9 DIGITS.

2023-08-07 07:36 UTC, neodc commented
Well, no? It's in `[]`, not `()`. So it allow any character in the class (so 0 or 1 here).

Proof: https://3v4l.org/g75AJ

2023-08-07 17:40 UTC, sstok approved these changes

2023-08-07 19:39 UTC, merged

2023-08-07 19:39 UTC, ddeboer commented
Thanks @neodc!